language: go

go:
  - "1.11.2"

# Enable building in Travis using forked repos.
go_import_path: sigs.k8s.io/cluster-api-provider-ibmcloud

dist: xenial

services:
  - docker

before_install:
  - bash -x ./hack/verify-docfiles.sh && DOC_ONLY=true && echo "Only doc files have changed!" || test true

# Install must be set to prevent default `go get` to run.
# The dependencies have already been vendored by `dep` so
# we don't need to fetch them.
install:
  -

script:
  - test $DOC_ONLY && echo "Skipped!" || bash -x ./scripts/pre-commit.sh

after_success:
  - test $DOC_ONLY && echo "Skipped!" || bash -x ./scripts/build-images.sh
