apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: cloud-config
  commands:
    clouds.yaml: "cat configs/clouds.yaml"
  type: Opaque

namespace: ibmcloud-provider-system
